### ISSUE TITLE
    op = os.listdir(output_dir)[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by emirhanai** [SwayamInSync/clothes-virtual-try-on#12]
INFO:werkzeug:127.0.0.1 - - [25/Jun/2023 02:02:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jun/2023 02:02:11] "GET /favicon.ico HTTP/1.1" 404 -
data recieved
ERROR:__main__:Exception on /api/transform [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-55-428f01ff33ec>", line 39, in begin
    op = os.listdir(output_dir)[0]
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [25/Jun/2023 02:02:48] "POST /api/transform HTTP/1.1" 500 -

**Comment by mishra-kunal** [comment]
Yeah facing same issue now.

**Comment by MosaabRkia** [comment]
Did any one found a solution?

**Comment by M-AWAIS786** [comment]
kindly provide the solution? facing same problem

**Comment by SwayamInSync** [comment]
Dealing with openpose issue on #19 
Please continue there and check my last comment
